version: '3.8'
networks:
  vue-express-crud-network:
    driver: bridge
services:
  vue-expressjs-crud-webapi:
    image: vue-expressjs-crud-webapi:v1
    depends_on:
      - express-mysql-db
    container_name: vue-expressjs-crud-webapi
    ports:
      - "8088:3000"
    build:
      context: ./express-crud-back
      dockerfile: dockerfile
    networks:
      - vue-express-crud-network

  express-mysql-db:
    image: vue-expressjs-crud-database:v1
    command: --default-authentication-plugin=mysql_native_password
    container_name: vue-expressjs-crud-database
    environment:
      - MYSQL_DATABASE=vueexpresscruddatabase
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3309:3306"
    build:
      context: ./express-crud-back/database-config
      dockerfile: Dockerfile
    restart: always
    volumes:
    - ./express-crud-back/dataaccess/mysql-data:/var/lib/mysql
    networks:
     - vue-express-crud-network

  vue-app:
    image: vue3-expressjs-crud-vue-app:v1
    container_name: vue3-expressjs-crud-vue-app
    build:
      context: ./vue-crud-front
      dockerfile: Dockerfile
    environment:
      - ENTORNO=localhost
    ports:
      - "8080:80" # Puedes mapear el puerto 80 del contenedor al puerto que prefieras en tu máquina local
    networks:
      - vue-express-crud-network

volumes:
  mysql-data: