apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  namespace: vue-expressjs-crud
spec:
  selector:
    app: webapi
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 5000