apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  namespace: vue-expressjs-crud
spec:
  selector:
    app: express-webapi
  ports:
    - protocol: TCP
      port: 5000  # Puerto externo del LoadBalancer
      targetPort: 3000  # Puerto del servicio interno
