apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  namespace: vue-expressjs-crud
spec:
  ports:
  - port: 30500
    targetPort: 3000
    protocol: TCP
  type: NodePort
  selector:
    app: express-webapi