apiVersion: v1
kind: Service
metadata:
  name: vue-app-service
  namespace: vue-expressjs-crud
spec:
  ports:
  - port: 30600
    targetPort: 80
    protocol: TCP
  type: NodePort
  selector:
    app: vue-app

