apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app-deployment
  namespace: vue-expressjs-crud
spec:
  replicas: 1  # Ajusta el número de réplicas según tus necesidades
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
      - name: app-container
        image: raptoverdad/vue-express-crud-front:master
        ports:
        - containerPort: 80
        env:
          - name: URL
            value: "af51824567d1941d08c1e31f3e8dce06-1892599787.sa-east-1.elb.amazonaws.com"
          # Agrega más variables de entorno según tus necesidades