apiVersion: v1
kind: Service
metadata:
  name: vue-app-service
  namespace: vue-expressjs-crud
spec:
  selector:
    app: vue-app  # Esto debe coincidir con la etiqueta de tu Deployment
  ports:
    - protocol: TCP
      port: 80  # Puerto externo del Service
      targetPort: 8080  # Puerto del contenedor que deseas exponer
  type: LoadBalancer  # Tipo de Service, puedes ajustarlo según tus necesidades