# Etapa 1: Utilizar una imagen base de Node.js para construir la aplicación
FROM node:18 as builder

RUN mkdir -p /app

WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app
RUN npm run build --prod

FROM nginx:alpine

# Copia los archivos de construcción de la aplicación desde la etapa de compilación anterior
COPY --from=builder /app/dist /usr/share/nginx/html

# Copia el contenido de nginxconfig.txt a nginx.conf
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf
#COPY ./_redirects /app/dist /usr/share/nginx/html

EXPOSE 80

# Comando para iniciar NGINX en el contenedor
CMD ["nginx", "-g", "daemon off;"]