on: push
name: deploy
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - vue-crud-front/dockerfile
          - express-crud-back/dockerfile
          - express-crud-back/database-config/dockerfile
        imagename:
          - rodrigomiranda/vue-express-crud-front:latest
          - rodrigomiranda/vue-express-crud-back:latest
          - rodrigomiranda/vue-express-crud-database:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        push: true
        tags: ${{ matrix.imagename }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}