on: push
name: deploy

jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: raptoverdad/vue-express-crud-front
            dockerfile: vue-crud-front/dockerfile
            context: ./vue-crud-front
          - image: raptoverdad/vue-express-crud-back
            dockerfile: express-crud-back/dockerfile
            context: ./express-crud-back
          - image: raptoverdad/vue-express-crud-database
            dockerfile: express-crud-back/database-config/dockerfile
            context: ./express-crud-back/database-config
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Configure AWS 
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set default.region ${{ secrets.AWS_REGION }}
      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name BABC-CLUSTER --region sa-east-1

      - name: delete vue app deployment
        run: kubectl delete deployment vue-app-deployment -n vue-expressjs-crud
      - name: delete db deployment
        run: kubectl delete deployment db-deployment -n vue-expressjs-crud
      - name: delete express api deployment  
        run: kubectl delete deployment webapi-deployment -n vue-expressjs-crud

      - name: delete vue app service
        run: kubectl delete service vue-app-service -n vue-expressjs-crud
      - name: delete db service
        run: kubectl delete service express-mysql-db -n vue-expressjs-crud
      - name: delete express api service  
        run: kubectl delete service webapi-service -n vue-expressjs-crud

      - name: Deploy vue app deployment to eks
        run: kubectl apply -f kubernetes/vue-app-deployment.yml
      - name: Deploy vue app service to eks
        run: kubectl apply -f kubernetes/vue-app-service.yml
      - name: Deploy express api deployment to eks
        run: kubectl apply -f kubernetes/express-api-deployment.yml
      - name: Deploy express api service to eks
        run: kubectl apply -f kubernetes/express-api-service.yml
      - name: Deploy database deployment to eks
        run: kubectl apply -f kubernetes/database-deployment.yml
      - name: Deploy database service to eks
        run: kubectl apply -f kubernetes/database-service.yml

